services:
  rinha:
    build:
      context: "."
      dockerfile: "./dockerfile"
    ports:
      - "9999:9999"
    environment:
      RINHA_ADDR: "0.0.0.0:9999"
      RINHA_UDS_PATH: "/tmp/rinha/rinha.sock"
