FROM rust:1.92 AS builder

WORKDIR /app
COPY . .
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12:nonroot AS runner

COPY --from=builder /app/target/release/server /app/

CMD ["/app/server"]
